// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"

	"github.com/foliet/account/rpc/internal/logic"
	"github.com/foliet/account/rpc/internal/svc"
	"github.com/foliet/account/rpc/pb"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) GetUser(ctx context.Context, in *pb.GetUserReq) (*pb.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
