// Code generated by goctl. DO NOT EDIT.
package types

type Status struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type SignInReq struct {
	AuthType  string   `json:"authType,options=phone|email|wechat"`
	AuthValue string   `json:"authValue"`
	Password  string   `json:"password,optional"`
	Options   []string `json:"options,optional"`
}

type SignInResp struct {
	Status
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}
