// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/xh-polaris/account-svc/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/send_verify_code",
				Handler: SendVerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sign_in",
				Handler: SignInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/set_password",
				Handler: SetPasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
