// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package account

import (
	"context"
	pb2 "github.com/xh-polaris/account-rpc/v2/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendVerifyCodeReq  = pb2.SendVerifyCodeReq
	SendVerifyCodeResp = pb2.SendVerifyCodeResp
	SetPasswordReq     = pb2.SetPasswordReq
	SetPasswordResp    = pb2.SetPasswordResp
	SignInReq          = pb2.SignInReq
	SignInResp         = pb2.SignInResp

	Account interface {
		SignIn(ctx context.Context, in *SignInReq, opts ...grpc.CallOption) (*SignInResp, error)
		SetPassword(ctx context.Context, in *SetPasswordReq, opts ...grpc.CallOption) (*SetPasswordResp, error)
		SendVerifyCode(ctx context.Context, in *SendVerifyCodeReq, opts ...grpc.CallOption) (*SendVerifyCodeResp, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) SignIn(ctx context.Context, in *SignInReq, opts ...grpc.CallOption) (*SignInResp, error) {
	client := pb2.NewAccountClient(m.cli.Conn())
	return client.SignIn(ctx, in, opts...)
}

func (m *defaultAccount) SetPassword(ctx context.Context, in *SetPasswordReq, opts ...grpc.CallOption) (*SetPasswordResp, error) {
	client := pb2.NewAccountClient(m.cli.Conn())
	return client.SetPassword(ctx, in, opts...)
}

func (m *defaultAccount) SendVerifyCode(ctx context.Context, in *SendVerifyCodeReq, opts ...grpc.CallOption) (*SendVerifyCodeResp, error) {
	client := pb2.NewAccountClient(m.cli.Conn())
	return client.SendVerifyCode(ctx, in, opts...)
}
